# fly.toml app configuration file generated for django-cf-r2-poetry on 2024-10-15T21:41:45-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'django-cf-r2-poetry'
primary_region = 'qro'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[mounts]
  source = "myapp_data"
  destination = "/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
